image: node:10.16.3 # change to match your project's node version

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf build
  - CI=false npm install

pages:
  stage: deploy
  script:
    - npm rebuild node-sass
    - CI=false npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  variables:
    PUBLIC_URL: "/sound-of-good-music/" # slash is important

  artifacts:
    paths:
      - public
  only:
    - master

