const ADD_USER = "ADD_USER"
const REMOVE_USER = "REMOVE_USER"
const ADD_TOKEN = "ADD_TOKEN"
const ADD_REFRESH_TOKEN = "ADD_REFRESH_TOKEN"
const ADD_ROLE = "ADD_ROLE"
const ADD_CURRENT_EVENT = "ADD_CURRENT_EVENT"

export { 
    ADD_USER,
    REMOVE_USER,
    ADD_TOKEN,
    ADD_REFRESH_TOKEN,
    ADD_ROLE,
    ADD_CURRENT_EVENT,
}
